
/* Drop Tables */

DROP TABLE TITLE_AUTHOR;
DROP TABLE AUTHORS;
DROP TABLE DISCOUNTS;
DROP TABLE EMPLOYEE;
DROP TABLE JOBS;
DROP TABLE ROYSCHED;
DROP TABLE SALES;
DROP TABLE TITLES;
DROP TABLE PUBLISHERS;
DROP TABLE PUBLISHERS_INFO;
DROP TABLE STORES;




/* Create Tables */

CREATE TABLE AUTHORS
(
	AU_ID VARCHAR(50) NOT NULL UNIQUE,
	AU_LNAME VARCHAR(200) NOT NULL,
	AU_FNAME VARCHAR(255) NOT NULL,
	PHONE VARCHAR(100),
	ADDRESS VARCHAR(1024),
	CITY VARCHAR(1024),
	ZIP CHAR(5),
	CONTRACT INT NOT NULL,
	STATE CHAR(2),
	PRIMARY KEY (AU_ID)
);


CREATE TABLE DISCOUNTS
(
	DISCCOUNT_TYPE VARCHAR(50) NOT NULL,
	STOR_ID CHAR(4),
	LOW_QTY INT,
	HIGH_QTY INT,
	DISCOUNT NUMERIC(20,4) NOT NULL
);


CREATE TABLE EMPLOYEE
(
	EMP_ID CHAR(9) NOT NULL UNIQUE,
	F_NAME VARCHAR(50) UNIQUE,
	-- M, R, F, G, W, N, H, A
	-- 
	-- middle name
	M_INIT CHAR(1),
	L_NAME VARCHAR(50),
	JOB_ID INT UNIQUE,
	-- job level
	JOB_LVL INT,
	PUB_ID INT NOT NULL,
	HIRE_DATE DATE,
	PRIMARY KEY (EMP_ID)
);


CREATE TABLE JOBS
(
	JOB_ID INT NOT NULL UNIQUE,
	JOB_DESCR VARCHAR(50) NOT NULL,
	PR_INFO VARCHAR(2048) NOT NULL,
	MAX_LVL FLOAT NOT NULL,
	PRIMARY KEY (JOB_ID)
);


CREATE TABLE PUBLISHERS
(
	PUB_ID INT NOT NULL UNIQUE,
	PUB_NAME VARCHAR(50) NOT NULL,
	CITY VARCHAR(50),
	STATE CHAR(2),
	COUNTRY VARCHAR(50),
	PRIMARY KEY (PUB_ID)
);


CREATE TABLE PUBLISHERS_INFO
(
	PUB_ID INT NOT NULL UNIQUE,
	LOGO BLOB(65536) NOT NULL,
	PR_INFO VARCHAR(2048) NOT NULL,
	PRIMARY KEY (PUB_ID)
);


CREATE TABLE ROYSCHED
(
	TITLE_ID VARCHAR(50) NOT NULL,
	LO_RANGE BIGINT,
	HI_RANGE BIGINT,
	ROYALITY BIGINT
);


CREATE TABLE SALES
(
	STOR_ID CHAR(4) NOT NULL,
	ORD_NUM VARCHAR(50) NOT NULL,
	TITLE_ID VARCHAR(50) NOT NULL,
	ORD_DATE DATE NOT NULL,
	QTY INT NOT NULL,
	-- npr. Net 60, ON invoice
	PAY_TERMS VARCHAR(50) NOT NULL,
	PRIMARY KEY (STOR_ID, ORD_NUM, TITLE_ID)
);


CREATE TABLE STORES
(
	STOR_ID CHAR(4) NOT NULL UNIQUE,
	STOR_NAME VARCHAR(50),
	STOR_ADDRESS VARCHAR(255),
	CITY VARCHAR(50),
	STATE CHAR(2),
	ZIP CHAR(5),
	PRIMARY KEY (STOR_ID)
);


CREATE TABLE TITLES
(
	TITLE_ID VARCHAR(50) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	TITLE_TYPE VARCHAR(12) NOT NULL,
	PUB_ID INT,
	PRICE DECIMAL(12,2),
	ADVANCE DECIMAL(12,2),
	ROYALITY BIGINT,
	YTD_SALES BIGINT,
	NOTES VARCHAR(200),
	PUB_DATE DATE NOT NULL,
	PRIMARY KEY (TITLE_ID)
);


CREATE TABLE TITLE_AUTHOR
(
	AU_ID VARCHAR(50) NOT NULL,
	TITLE_ID VARCHAR(50) NOT NULL,
	AU_ORD INT,
	ROYALTYPER INT,
	PRIMARY KEY (AU_ID, TITLE_ID)
);



/* Create Foreign Keys */

ALTER TABLE TITLE_AUTHOR
	ADD FOREIGN KEY (AU_ID)
	REFERENCES AUTHORS (AU_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (PUB_ID)
	REFERENCES PUBLISHERS (PUB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TITLES
	ADD FOREIGN KEY (PUB_ID)
	REFERENCES PUBLISHERS (PUB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PUBLISHERS
	ADD FOREIGN KEY (PUB_ID)
	REFERENCES PUBLISHERS_INFO (PUB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISCOUNTS
	ADD FOREIGN KEY (STOR_ID)
	REFERENCES STORES (STOR_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SALES
	ADD FOREIGN KEY (STOR_ID)
	REFERENCES STORES (STOR_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ROYSCHED
	ADD FOREIGN KEY (TITLE_ID)
	REFERENCES TITLES (TITLE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SALES
	ADD FOREIGN KEY (TITLE_ID)
	REFERENCES TITLES (TITLE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TITLE_AUTHOR
	ADD FOREIGN KEY (TITLE_ID)
	REFERENCES TITLES (TITLE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



