
/* Drop Tables */

DROP TABLE IF EXISTS ISPIT;
DROP TABLE IF EXISTS N_PREDAJE_P;
DROP TABLE IF EXISTS NASTAVNIK;
DROP TABLE IF EXISTS P_SLUSA_S;
DROP TABLE IF EXISTS PREDMET;
DROP TABLE IF EXISTS STUDENT;




/* Create Tables */

CREATE TABLE ISPIT
(
	ID_PREDMET INTEGER NOT NULL,
	ID_NASTAVNIK INTEGER NOT NULL,
	ID_STUDENT INTEGER NOT NULL,
	VRIJEME DATE,
	PRIMARY KEY (ID_PREDMET, ID_NASTAVNIK)
) WITHOUT OIDS;


CREATE TABLE NASTAVNIK
(
	ID_NASTAVNIK INTEGER NOT NULL,
	NAZIV VARCHAR(100),
	PRIMARY KEY (ID_NASTAVNIK)
) WITHOUT OIDS;


CREATE TABLE N_PREDAJE_P
(
	ID_NASTAVNIK INTEGER NOT NULL,
	ID_PREDMET INTEGER NOT NULL,
	BODOVA INTEGER,
	PRIMARY KEY (ID_NASTAVNIK, ID_PREDMET)
) WITHOUT OIDS;


CREATE TABLE PREDMET
(
	ID_PREDMET INTEGER NOT NULL,
	NAZIV VARCHAR(200),
	PRIMARY KEY (ID_PREDMET)
) WITHOUT OIDS;


CREATE TABLE P_SLUSA_S
(
	ID_STUDENT INTEGER NOT NULL,
	ID_PREDMET INTEGER NOT NULL,
	SEMESTAR INTEGER,
	PRIMARY KEY (ID_STUDENT, ID_PREDMET)
) WITHOUT OIDS;


CREATE TABLE STUDENT
(
	ID_STUDENT INTEGER NOT NULL,
	NAZIV VARCHAR(100),
	PRIMARY KEY (ID_STUDENT)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE N_PREDAJE_P
	ADD FOREIGN KEY (ID_NASTAVNIK)
	REFERENCES NASTAVNIK (ID_NASTAVNIK)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ISPIT
	ADD FOREIGN KEY (ID_PREDMET, ID_NASTAVNIK)
	REFERENCES N_PREDAJE_P (ID_PREDMET, ID_NASTAVNIK)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE N_PREDAJE_P
	ADD FOREIGN KEY (ID_PREDMET)
	REFERENCES PREDMET (ID_PREDMET)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE P_SLUSA_S
	ADD FOREIGN KEY (ID_PREDMET)
	REFERENCES PREDMET (ID_PREDMET)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ISPIT
	ADD FOREIGN KEY (ID_PREDMET, ID_STUDENT)
	REFERENCES P_SLUSA_S (ID_PREDMET, ID_STUDENT)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE P_SLUSA_S
	ADD FOREIGN KEY (ID_STUDENT)
	REFERENCES STUDENT (ID_STUDENT)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



